[workspace]
members = ["crates/kitchen", "crates/kitchen-cli"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98.1"
authors = ["lemarier"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lemarier/kitchen"
publish = false

[workspace.dependencies]
clap = { version = "4.6.7", features = ["derive"] }
kitchen = { path = "crates/kitchen", version = "0.1.0" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tempfile = "3.27.0"
tera = { version = "2.4.0", default-features = false }
thiserror = "2.0.21"
sha2 = { version = "0.11.0", default-features = false }
time = { version = "0.3.55", features = ["parsing", "formatting"] }
toml = { version = "1.1.6", default-features = false, features = ["parse", "serde", "std"] }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
